name: CD

on:
  workflow_run:
    workflows: ["Build and Deploy Custom Image"]
    types:
      - completed

jobs:
  dev-share-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_github_action }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_github_action }}

      - name: Verify AWS CLI
        run: aws s3 ls

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Share AMI with demo
        run: |
          IMAGE_ID=$(
              aws ec2 describe-images \
              --owners $(aws sts get-caller-identity --query Account --output text) \
              --filters "Name=name,Values=csye6225_app*" \
              --query 'Images[*].[ImageId,Name,CreationDate]' \
              --output json | jq -r 'sort_by(.[2]) | last | .[0]'
          )
          
          echo "Latest AMI ID: $IMAGE_ID"
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          
          aws ec2 modify-image-attribute \
            --image-id $IMAGE_ID\
            --launch-permission "Add=[{UserId=${{ secrets.AWS_DEMO_ID }}}]"

      - name: Configure AWS CLI for demo user
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_AK_DEMO }}
          aws-secret-access-key: ${{ secrets.AWS_SAK_DEMO }}
          aws-region: us-east-1

      - name: Create new template and update ASG
        run: |
          LT_ID=$(aws ec2 describe-launch-templates \
            --region us-east-1\
            --query "LaunchTemplates[?starts_with(LaunchTemplateName, 'webapp_lt')].LaunchTemplateId" \
            --output text)
          
          echo "Launch Template ID: $LT_ID"
          
          echo "LT_ID=$LT_ID" >> $GITHUB_ENV

          
