name: Test webapp

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    name: webapp test
    runs-on: ubuntu-latest

    services:
      mysql:
         image: mysql:8.0
         env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD}}

         ports:
           - 3306: 3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Starting MySQL Service...
        run: |
          echo "等待 MySQL 服务启动..."
          while ! mysqladmin ping -h 127.0.0.1 -P 3306 --silent; do
            sleep 5
          done
          echo "MySQL 启动成功！"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r webappFlask/requirements.txt


      - name: Run tests
        run: python webappFlask/test/test_healthz.py
