name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  run-tests:
    name: Run test.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: echo password
        run: echo ${{ secrets.MYSQL_PASSWORD }}

      - name: SetUp MySQL
        if: github.event.pull_request.head.repo.fork == false
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: '' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check mysql status
        run: ss -tln | grep 3306


      - name: Install dependencies and Run tests
        env:
         MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
         MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
         WEBAPP_SECRET_KEY: ${{ secrets.WEBAPP_SECRET_KEY }}
         WEBAPP_AES_SECRET_KEY: ${{ secrets.WEBAPP_AES_SECRET_KEY }}
         WEBAPP_PUBLIC_KEY: ${{ secrets.WEBAPP_PUBLIC_KEY }}
         WEBAPP_PRIVATE_KEY: ${{ secrets.WEBAPP_PRIVATE_KEY }}
        run: | 
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip3 install -r webappFlask/requirements.txt && pwd && cd ./webappFlask && pip list && python manage.py runserver && python webappFlask/test/test_healthz.py
